openapi: 3.0.1
info:
  title: Email Notification Microservice
  description: The API documentation for Email notification microservice APIs

  license:
    name: Apache 2.0
  version: 1.0.0
servers:
  - url: http://localhost:5000/v1/notification/
    description: DEV environnement
  - url: http://localhost:5000/v1/notification/
    description: QA environnement
tags:
  - name: Health Check
    description: Health check related APIs
  - name: Push Notification
    description: Notification service related APIs

paths:

  /email/push-notification:
    post:
      tags:
        - Push Notification
      summary: Send a new notification task
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/notificationServicePostRequest'
      responses:
        201:
          description: successful operation
          headers:
            correlation-id:
              schema:
                type: string
                format: uuid
              description: correlation id (uuid)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notificationServiceResponseBody'
        400:
          description: bad request
          headers:
            correlation-id:
              schema:
                type: string
                format: uuid
              description: correlation id (uuid)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notificationServiceBadRequest'   
    
  /healthcheck:
    get:
      tags:
        - Health Check
      summary: Health check root API
      responses:
        200:
          description: successful operation
          headers:
            correlation-id:
              schema:
                type: string
                format: uuid
              description: correlation id (uuid)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getHealthCheckResponseBody'
        500:
          $ref: '#/components/responses/InternalServerError'

    
components:
  responses:
    InternalServerError:
      description: Unexpected error
      headers:
        correlation-id:
          schema:
            type: string
            format: uuid
          description: correlation id (uuid)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerError'
            
  schemas:
    notificationServicePostRequest:
        required:
        - applicationName
        - emailCategory
        - template
        - templateData
        - toAddresses
        - ccAddresses
        - bccAddresses
        type: object
        properties:
          applicationName:
            type: string
            example : "notification_service"
          emailCategory:
            type: string
            example: "error_notification"
          template:
            format: date
            type: string
            example : "error_notification_template"
          templateData:
            type: object
            required:
            - subject
            - dateTime
            - userEmail
            - message
            - message2
            properties:
              subject:
                type: string
                example: "Notification Email "
              dateTime:
                type: string
                example: "06-02-2020 19:23:23"
              userEmail:
                type: string
                example: "test@user.com"
              message:
                type: string
                example: "Hello"
              message2:
                type: string
                example: "Completed"
          toAddresses:
            type: array
            items:
              type: string
            example: ["user1@gmail.com", "user2@gmail.com", "user3@gmail.com"]
          ccAddresses:
            type: array
            items:
              type: string
            example: ["user1@gmail.com", "user2@gmail.com", "user3@gmail.com"]
          bccAddresses:
            type: array
            items:
              type: string
            example: ["user1@gmail.com", "user2@gmail.com", "user3@gmail.com"]


    notificationServiceResponseBody:
      required:
        - status
        - data
      type: object
      properties:
        status:
          type: string
          example: "success"
        data:
          type: array
          items:
            required:
            - requestId
            - isSuccess
            type: object
            properties:
              requestId:
                type: string
                example: "b57ca4ce-be31-4d5a-878d-3fafc3724e14"
              isSuccess:
                type: boolean
                example: true

    HealthCheckResponseObject:
      required:
        - uptime
        - memoryUsage
        - nodeVersion
        - nodeEnv
        - versionId
      type: object
      properties:
        uptime:
          type: number
          example: 374.49
        memoryUsage:
          type: object
          properties:
            rss:
              type: number
              example: 83775488
            heapTotal:
              type: number
              example: 64307200
            heapUsed:
              type: number
              example: 33764816
            external:
              type: number
              example: 1329499
        nodeVersion:
          type: string
          example: "10.19.0"
        nodeEnv:
          type: string
          example: "production"
        versionId:
         type: string
         example: "123DSye"

    getHealthCheckResponseBody:
      type: object
      properties:
        status:
          type: string
          enum:
            - success
            - error
        data:
          type: object
          allOf:
            - $ref: '#/components/schemas/HealthCheckResponseObject'
    InternalServerError:
      type: object
      properties:
        status:
          type: string
          enum:
            - error
          example: error
        data:
          type: object
          properties:
            message:
              type: string
              example: 'Internal server error'
            correlationId:
              type: string
              example: "a92f273a-58b3-443c-97a6-e9498d461ef2"  

          
    notificationServiceBadRequest:
      type: object
      properties:
        status:
          type: string
          enum:
            - error
          example: error
        data:
          type: object
          properties:
            message:
              type: string
              example: "should have required property 'applicationName'"
            correlationId:
              type: string
              example: "a92f273a-58b3-443c-97a6-e9498d461ef2"